#!/usr/bin/python3

from os.path import *
from utils.banner import get_banner
from utils.load_url_blueprints import load_urls
import click
from colorama import Fore, Back, Style


@click.command()
@click.option("--username", "-u", help="Specify username for the target to be hunted")
@click.option("--blueprint", "-b", help="Specify the path to the blueprint", default=None)
def main(username, blueprint):
    banner = get_banner()
    print(Fore.RED+banner)

    urls = load_urls()

    if blueprint is not None:
        try:
            urls = load_urls(expanduser(blueprint))
        except Exception as pathE:
            print(Fore.RED+ f"An Error occured <: {pathE}")
            exit()

    print(Fore.GREEN+"Urls Loaded Successfully!!")



if __name__ == "__main__":
    main()
